### ISSUE TITLE
after some inserts it gives error

### ISSUE THREAD

**Issue by Miamoto-Musashi** [eversign/eversign-python-sdk#16]
**Describe the bug**
Adding fields to a template 

**To Reproduce**
use this code
```
       template = eversign.Template()
        template.sandbox = True
        template.template_id = 'c5876f4e0a3940d88218f7f173601558'
        template.title = 'carrier broker agreement'
        template.message = f'hello, {carrier["name"]}'

        template.embedded_signing_enabled = True

        broker = eversign.Signer(
            name=carrier['ceo']['name'],
            email=carrier['email'],
            role='carrier')
        ceo = eversign.Signer(
            name='CEO',
            email='some@example.com',
            role='broker')

        template.add_signer(broker)
        template.add_signer(ceo)

        # carrier name
        field = eversign.TextField()
        field.identifier = 'carrier_name'
        field.value = carrier['name']
        template.add_field(field)

        # carrier MC
        field = eversign.TextField()
        field.identifier = 'carrier_mc'
        field.value = carrier['mc']
        template.add_field(field)

        # carrier DOT
        field = eversign.TextField()
        field.identifier = 'carrier_dot'
        field.value = carrier['dot']
        template.add_field(field)

        # Carrier CEO name
        field = eversign.TextField
        field.identifier = 'carrier_ceo_name'
        field.value = carrier['ceo']['name']
        template.add_field(field)
```
**Expected behavior**
should add field like the other fields but gives error

**Screenshots**
```
  File "contracts.py", line 54, in create_carrier_agreement
    template.add_field(field)
  File "/venv/lib/python3.8/site-packages/eversign/document.py", line 111, in add_field
    return self.add_field_list([field])
  File "/venv/lib/python3.8/site-packages/eversign/document.py", line 115, in add_field_list
    field.validate()
TypeError: validate() missing 1 required positional argument: 'self'

127.0.0.1 - - [15/Nov/2020 01:37:16] "POST /organizations/%7Bkey%7D/contracts HTTP/1.1" 500 -
organizations - ERROR - Caught exception for path /organizations/{key}/contracts
Traceback (most recent call last):
  File ".../venv/lib/python3.8/site-packages/chalice/app.py", line 1683, in _get_view_function_response
    response = view_function(**function_args)
  File "app.py", line 232, in send_contract
    get_contracts_client().create_carrier_agreement(carrier)
  File "contracts.py", line 54, in create_carrier_agreement
    template.add_field(field)
  File "..../.chalice/venv/lib/python3.8/site-packages/eversign/document.py", line 111, in add_field
    return self.add_field_list([field])
  File ".../.chalice/venv/lib/python3.8/site-packages/eversign/document.py", line 115, in add_field_list
    field.validate()
TypeError: validate() missing 1 required positional argument: 'self'

```
**Desktop (please complete the following information):**
 - OS: MacOs

**Additional context**

template is
https://packoff.eversign.com/templates/c5876f4e0a3940d88218f7f173601558

BR

**Comment by milanlatinovic** [comment]
Hi @Miamoto-Musashi, before debugging this in details, just to doublecheck this part of the code
```  
# Carrier CEO name
field = eversign.TextField
```

Are you missing function call () at TextField, can you try 
```  
# Carrier CEO name
field = eversign.TextField()
```

Let me know if this solved your issue or is it still present.

**Comment by milanlatinovic** [comment]
Since there was no activity for this issue for 5+ days I will assume issue was related to the missing function call.
I am closing this issue now.
