### ISSUE TITLE
schematics.exceptions.DataError

### ISSUE THREAD

**Issue by BenHagan** [eversign/eversign-python-sdk#8]
Getting an error from the schematics library upon calling `client.create_document_from_template()`:

`schematics.exceptions.DataError: {"width": ["Couldn't interpret '111.13' as string."], "height": ["Couldn't interpret '11.63' as string."]}`

I'm using an existing template, id = UOYXfCBKn3B5Nc.

Could this possibly be an issue with my template?  Using python 3.7.3.

Full trace:
`Traceback (most recent call last):
  File "/home/ben/.virtualenvs/coop/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ben/.virtualenvs/coop/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ben/.virtualenvs/coop/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ben/.virtualenvs/coop/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ben/Documents/code/coop/coop/employees/views.py", line 34, in create_new_employee_view
    user.email
  File "/home/ben/Documents/code/coop/coop/employees/api/eversign.py", line 25, in create_eversign_new_hire_doc
    client.create_document_from_template(template)
  File "/home/ben/.virtualenvs/coop/lib/python3.7/site-packages/eversign/client.py", line 166, in create_document_from_template
    return self._request('/document', method='POST', data=data, return_type=Document)
  File "/home/ben/.virtualenvs/coop/lib/python3.7/site-packages/eversign/client.py", line 512, in _request
    return self._serialize(response_obj, return_type)
  File "/home/ben/.virtualenvs/coop/lib/python3.7/site-packages/eversign/client.py", line 523, in _serialize
    return model(**object)
  File "/home/ben/.virtualenvs/coop/lib/python3.7/site-packages/eversign/document.py", line 32, in __init__
    kw, kwargs, mapping[kw][0])
  File "/home/ben/.virtualenvs/coop/lib/python3.7/site-packages/eversign/document.py", line 68, in from_object
    lst.append(_class(**element))
  File "/home/ben/.virtualenvs/coop/lib/python3.7/site-packages/eversign/field.py", line 18, in __init__
    self.__dict__['_model'] = FieldModel(kwargs, strict=False)
  File "/home/ben/.virtualenvs/coop/lib/python3.7/site-packages/schematics/models.py", line 235, in __init__
    app_data=app_data, **kwargs)
  File "/home/ben/.virtualenvs/coop/lib/python3.7/site-packages/schematics/models.py", line 299, in _convert
    return func(self._schema, self, raw_data=raw_data, oo=True, context=context, **kwargs)
  File "/home/ben/.virtualenvs/coop/lib/python3.7/site-packages/schematics/transforms.py", line 428, in convert
    return import_loop(cls, mutable, raw_data, import_converter, **kwargs)
  File "/home/ben/.virtualenvs/coop/lib/python3.7/site-packages/schematics/transforms.py", line 174, in import_loop
    raise DataError(errors, data)
schematics.exceptions.DataError: {"width": ["Couldn't interpret '111.13' as string."], "height": ["Couldn't interpret '11.63' as string."]}`

**Comment by dominikkukacka** [comment]
Sorry we completely overlooked the issue.
Is this still an issue?
